version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 0.68.2
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.40.0
    - 2.41.0
    - 2.41.1
    - 2.41.2
    - 2.41.4
    - 2.41.5
    - 2.42.1
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
    - 2.45.2
  - dependency-name: react-scripts
    versions:
    - 4.0.2
