# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        node-version: [9.x, 10.x, 12.x, 14.x, 15.x]
        os: [ubuntu-latest, windows-latest, macos-latest, windows-2019, ubuntu-20.04, ubuntu-18.04, ubuntu-16.04, macos-10.15]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn run build
    - run: yarn run test
